import { readFileSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { afterEach, describe, expect, it } from 'vitest'

import type { Catalog } from '../src/catalog/types'
import type { Tutorial } from '../src/schema/types'
import type { TracedDrawing } from '../src/trace/traceSvg'

import type { BrowserBridge } from './bridge'
import { openTestStudio, type TestStudio } from './testing'

const PNG = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0, 0, 0, 0])
const SVG = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x="10" y="10" width="80" height="80" fill="#E8C872"/></svg>'
const fixture = (name: string) => readFileSync(fileURLToPath(new URL(`../server/fixtures/${name}`, import.meta.url)), 'utf8')

const line = (id: string, d: string) => ({ id, d, lineWidth: 6, color: undefined, length: 200, box: [100, 100, 300, 300] as [number, number, number, number], closed: false, origin: 'outline' as const })

/** A traced square: three lines and two colours, as `generateFromTrace.test.ts` uses. */
const trace = (): TracedDrawing => ({
  canvas: { width: 1000, height: 1000 },
  strokes: [line('s1', 'M 100 100 L 300 100'), line('s2', 'M 100 100 L 100 300'), line('s3', 'M 300 100 L 300 300')],
  fills: [
    { id: 'f1', d: 'M 100 100 L 300 100 L 300 300 L 100 300 Z', color: '#E8C872', area: 40000, box: [100, 100, 300, 300] },
    { id: 'f2', d: 'M 150 150 L 250 150 L 250 250 L 150 250 Z', color: '#1F3A5F', area: 10000, box: [150, 150, 250, 250] },
  ],
  notes: ['Traced for the test.'],
  outlineCoverage: 1,
})

const analysis = { mainForms: ['a square'], importantDetails: [], detailsRemoved: [], drawingStrategy: 'The top edge first.' }

/** A model that always gives `answer`, recording what it was sent. */
function model(answer: unknown) {
  const calls: { body: Record<string, unknown> }[] = []
  const fetch = (async (_url: string, init: RequestInit) => {
    calls.push({ body: JSON.parse(String(init.body)) })
    const payload = {
      model: 'vendor/text-model',
      choices: [{ finish_reason: 'stop', message: { content: typeof answer === 'string' ? answer : JSON.stringify(answer) } }],
      usage: { prompt_tokens: 900, completion_tokens: 400, cost: 0.004 },
    }
    return new Response(JSON.stringify(payload), { status: 200, headers: { 'Content-Type': 'application/json' } })
  }) as unknown as typeof globalThis.fetch
  return { calls, fetch }
}

/** A browser that traces every SVG to the square and renders every picture to the tiny PNG. */
function browser(): BrowserBridge & { traced: number } {
  const bridge = {
    traced: 0,
    async trace() {
      bridge.traced += 1
      return trace()
    },
    async renderPng() {
      return PNG.toString('base64')
    },
    async drawingPng() {
      return PNG.toString('base64')
    },
    async optimize() {
      throw new Error('not in these tests')
    },
    async close() {},
  }
  return bridge
}

let t: TestStudio

afterEach(async () => {
  await t?.close()
})

async function open(answer: unknown, options: { key?: boolean } = {}) {
  const router = model(answer)
  const bridge = browser()
  t = await openTestStudio({
    generation: { apiKey: options.key === false ? undefined : 'test-key', defaultModel: 'vendor/text-model', fetch: router.fetch },
    browser: bridge,
  })
  return { router, bridge }
}

async function catalog(): Promise<Catalog> {
  const { paths, lessons } = await t.workspace.readCatalog()
  return { paths: JSON.parse(paths.text).paths, lessons: JSON.parse(lessons.text).lessons }
}

const common = ['--title', 'Cottage', '--objective', 'A cottage from a box', '--goal', 'Draw a cottage.', '--source', 'me', '--license', 'CC0']

describe('image to-steps', () => {
  it('generates from a photo and keeps the draft, its photo, its catalog entry and its history', async () => {
    const { router } = await open(JSON.parse(fixture('generation-cottage.json')))
    const photo = path.join(t.root, 'cottage.png')
    await writeFile(photo, PNG)
    const outcome = await t.studio(['image', 'to-steps', photo, '--id', 'cottage', ...common, '--path', 'houses', '--position', '1'])
    expect(outcome.stderr).toBe('')
    expect(outcome.code).toBe(0)
    expect(outcome.stdout).toContain('Generated by vendor/text-model (lesson-v1), $0.0040.')
    expect(outcome.stdout).toContain('Kept as the draft cottage at 1 in "houses", with cottage.png as its reference.')
    expect(router.calls).toHaveLength(1)

    const stored = JSON.parse((await t.workspace.readTutorial('cottage'))!.text) as Tutorial
    expect(stored.id).toBe('cottage')
    expect(stored.title).toBe('Cottage')
    const entry = (await catalog()).lessons.find((l) => l.id === 'cottage')
    expect(entry).toMatchObject({ status: 'draft', objective: 'A cottage from a box', reference: { file: 'cottage.png', source: 'me', license: 'CC0' } })
    expect(entry?.generation).toMatchObject({ model: 'vendor/text-model', promptVersion: 'lesson-v1', goal: 'Draw a cottage.' })
    expect((await catalog()).paths[1].lessonIds).toEqual(['cottage', 'simple-house'])
    const history = await t.workspace.readHistory('cottage')
    expect(history.map((e) => [e.kind, e.kept, e.cost])).toEqual([['generated', true, 0.004]])
    expect((await t.workspace.readReference('cottage.png'))?.bytes.byteLength).toBe(12)
  })

  it('refuses a taken id before asking the model', async () => {
    const { router } = await open({})
    const photo = path.join(t.root, 'p.png')
    await writeFile(photo, PNG)
    const outcome = await t.studio(['image', 'to-steps', photo, '--id', 'simple-house', ...common])
    expect(outcome.code).toBe(1)
    expect(outcome.stderr).toContain('already exists')
    expect(router.calls).toHaveLength(0)
  })

  it('refuses an SVG, and svg to-steps refuses a photo', async () => {
    await open({})
    const svg = path.join(t.root, 'a.svg')
    await writeFile(svg, SVG)
    const photo = path.join(t.root, 'p.png')
    await writeFile(photo, PNG)
    expect((await t.studio(['image', 'to-steps', svg, '--id', 'x', ...common])).stderr).toContain('svg to-steps')
    expect((await t.studio(['svg', 'to-steps', photo, '--id', 'x', ...common])).stderr).toContain('image to-steps')
  })

  it('keeps nothing when the model’s answer is invalid, and can write it out to inspect', async () => {
    const { router } = await open(JSON.parse(fixture('generation-arc.json')))
    const photo = path.join(t.root, 'p.png')
    await writeFile(photo, PNG)
    const out = path.join(t.root, 'bad.json')
    const outcome = await t.studio(['image', 'to-steps', photo, '--id', 'arc', ...common, '--out', out])
    expect(outcome.code).toBe(1)
    expect(outcome.stderr).toContain('not a valid lesson')
    expect(outcome.stderr).toContain('duration')
    expect(router.calls).toHaveLength(1)
    expect(await t.workspace.readTutorial('arc')).toBeNull()
    expect(JSON.parse(await readFile(out, 'utf8'))).toHaveProperty('issues')
  })

  it('says what it would send with --dry-run, and needs a key otherwise', async () => {
    const { router } = await open({}, { key: false })
    const photo = path.join(t.root, 'p.png')
    await writeFile(photo, PNG)
    const dry = await t.studio(['image', 'to-steps', photo, '--id', 'x', ...common, '--dry-run'])
    expect(dry.code).toBe(0)
    expect(dry.stdout).toContain('key missing')
    const real = await t.studio(['image', 'to-steps', photo, '--id', 'x', ...common])
    expect(real.code).toBe(1)
    expect(real.stderr).toContain('OPENROUTER_API_KEY')
    expect(router.calls).toHaveLength(0)
  })
})

describe('svg to-steps', () => {
  const answer = {
    analysis,
    outlineSteps: [{ id: 'top', title: 'The top', instruction: 'Draw the top edge.', strokeIds: ['s1'] }, { id: 'sides', title: 'The sides', instruction: 'Both sides.', strokeIds: ['s2', 's3'] }],
    colourSteps: [{ id: 'paint', title: 'Colour', instruction: 'Colour it.', fillIds: ['f1', 'f2'] }],
  }

  it('traces the file in the browser, sends the trace, and keeps a v2 lesson with the SVG as its reference', async () => {
    const { router, bridge } = await open(answer)
    const svg = path.join(t.root, 'square.svg')
    await writeFile(svg, SVG)
    const outcome = await t.studio(['svg', 'to-steps', svg, '--id', 'square', ...common, '--max-strokes', '32'])
    expect(outcome.stderr).toBe('')
    expect(outcome.code).toBe(0)
    expect(bridge.traced).toBe(1)
    expect(router.calls).toHaveLength(1)
    expect(JSON.stringify(router.calls[0].body)).toContain('s1')

    const stored = JSON.parse((await t.workspace.readTutorial('square'))!.text) as Tutorial
    expect(stored.schemaVersion).toBe(2)
    expect(stored.steps.map((s) => s.id)).toEqual(['top', 'sides', 'paint'])
    expect((await catalog()).lessons.find((l) => l.id === 'square')?.reference?.file).toBe('square.svg')
    expect((await catalog()).lessons.find((l) => l.id === 'square')?.generation?.promptVersion).toBe('svg-lesson-v1')
  })

  it('takes a saved trace instead of tracing again', async () => {
    const { bridge } = await open(answer)
    const svg = path.join(t.root, 'square.svg')
    await writeFile(svg, SVG)
    const saved = path.join(t.root, 'trace.json')
    await writeFile(saved, JSON.stringify(trace()))
    const outcome = await t.studio(['svg', 'to-steps', svg, '--id', 'square', ...common, '--trace', saved])
    expect(outcome.code).toBe(0)
    expect(bridge.traced).toBe(0)
  })

  it('builds a lesson from the trace alone with --no-model, a few lines per step', async () => {
    const { router } = await open(answer)
    const svg = path.join(t.root, 'square.svg')
    await writeFile(svg, SVG)
    const outcome = await t.studio(['svg', 'to-steps', svg, '--id', 'square', '--no-model', '--title', 'Square', '--objective', 'A square', '--source', 'me', '--license', 'CC0'])
    expect(outcome.stderr).toBe('')
    expect(outcome.code).toBe(0)
    expect(outcome.stdout).toContain('without a model')
    expect(router.calls).toHaveLength(0)
    const stored = JSON.parse((await t.workspace.readTutorial('square'))!.text) as Tutorial
    expect(stored.steps.map((s) => [s.id, s.strokes.length, s.fills?.length ?? 0])).toEqual([['lines-1', 3, 0], ['colour', 0, 2]])
    expect((await catalog()).lessons.find((l) => l.id === 'square')?.generation).toBeUndefined()
    expect((await t.workspace.readHistory('square')).map((e) => e.kind)).toEqual(['generated'])
  })

  it('shows and writes the candidate without keeping it, with --no-keep', async () => {
    await open(answer)
    const svg = path.join(t.root, 'square.svg')
    await writeFile(svg, SVG)
    const out = path.join(t.root, 'candidate.json')
    const outcome = await t.studio(['svg', 'to-steps', svg, '--id', 'square', ...common, '--no-keep', '--out', out])
    expect(outcome.code).toBe(0)
    expect(outcome.stdout).toContain('Not kept')
    expect(await t.workspace.readTutorial('square')).toBeNull()
    expect((JSON.parse(await readFile(out, 'utf8')) as { tutorial: Tutorial }).tutorial.id).toBe('square')
  })
})

describe('lessons regenerate', () => {
  const answer = {
    rationale: 'Each instruction now says where to start.',
    steps: [
      { id: 'walls', title: 'Walls', instruction: 'Start at the top left.' },
      { id: 'roof', title: 'Roof', instruction: 'Start at the left eave.' },
      { id: 'door', title: 'Door', instruction: 'Centre it.' },
      { id: 'windows', title: 'Windows', instruction: 'Either side.' },
      { id: 'chimney', title: 'Chimney', instruction: 'On the right.' },
    ],
  }

  it('records the regenerated layer in History and leaves the lesson as it was', async () => {
    const { router } = await open(answer)
    const outcome = await t.studio(['lessons', 'regenerate', 'simple-house', '--layer', 'instructions', '--note', 'Say where to start.'])
    expect(outcome.stderr).toBe('')
    expect(outcome.code).toBe(0)
    expect(outcome.stdout).toContain('Rationale: Each instruction now says where to start.')
    expect(router.calls).toHaveLength(1)
    expect(JSON.stringify(router.calls[0].body)).toContain('Say where to start.')
    const history = await t.workspace.readHistory('simple-house')
    expect(history.map((e) => [e.kind, e.layer, e.note])).toEqual([
      ['regenerated', 'instructions', 'Say where to start.'],
      ['saved', undefined, undefined],
    ])
    expect(history[0].tutorial.steps[0].title).toBe('Walls')
    expect((JSON.parse((await t.workspace.readTutorial('simple-house'))!.text) as Tutorial).steps[0].title).toBe('Draw the walls')
  })

  it('makes the regenerated version the lesson with --use', async () => {
    await open(answer)
    const outcome = await t.studio(['lessons', 'regenerate', 'simple-house', '--layer', 'instructions', '--use'])
    expect(outcome.code).toBe(0)
    expect((JSON.parse((await t.workspace.readTutorial('simple-house'))!.text) as Tutorial).steps[0].title).toBe('Walls')
    expect((await t.workspace.readHistory('simple-house')).map((e) => e.kind)).toEqual(['saved', 'regenerated', 'saved'])
  })

  it('needs a reference for a new drawing, and says what it would send with --dry-run', async () => {
    const { router } = await open(answer)
    const missing = await t.studio(['lessons', 'regenerate', 'simple-house', '--layer', 'drawing'])
    expect(missing.code).toBe(1)
    expect(missing.stderr).toContain('has none')
    const dry = await t.studio(['lessons', 'regenerate', 'palm-tree-4', '--layer', 'drawing', '--dry-run'])
    expect(dry.code).toBe(0)
    expect(dry.stdout).toContain('Reference: palm-tree-4.svg (image/svg+xml).')
    expect(router.calls).toHaveLength(0)
  })

  it('regenerates a drawing from an SVG reference through the tracer', async () => {
    const { router, bridge } = await open({
      analysis,
      outlineSteps: [{ id: 'all', title: 'All', instruction: 'All lines.', strokeIds: ['s1', 's2', 's3'] }],
      colourSteps: [{ id: 'paint', title: 'Colour', instruction: 'Colour it.', fillIds: ['f1', 'f2'] }],
    })
    const outcome = await t.studio(['lessons', 'regenerate', 'palm-tree-4', '--layer', 'drawing', '--goal', 'A palm', '--use'])
    expect(outcome.stderr).toBe('')
    expect(outcome.code).toBe(0)
    expect(bridge.traced).toBe(1)
    expect(router.calls).toHaveLength(1)
    const stored = JSON.parse((await t.workspace.readTutorial('palm-tree-4'))!.text) as Tutorial
    expect(stored.steps.map((s) => s.id)).toEqual(['all', 'paint'])
    expect(stored.title).toBe('Palm Tree 4')
  })
})
