import { readFileSync } from 'node:fs'
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { afterEach, describe, expect, it } from 'vitest'

import type { Catalog } from '../src/catalog/types'
import type { Tutorial } from '../src/schema/types'

import { PNG_BYTES as PNG, fakeBrowser, openTestStudio, squareTrace as trace, type TestStudio } from './testing'

const SVG = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect x="10" y="10" width="80" height="80" fill="#E8C872"/></svg>'
const fixture = (name: string) => readFileSync(fileURLToPath(new URL(`../server/fixtures/${name}`, import.meta.url)), 'utf8')

const analysis = { mainForms: ['a square'], importantDetails: [], detailsRemoved: [], drawingStrategy: 'The top edge first.' }

/** A model that always gives `answer`, recording what it was sent. */
function model(answer: unknown) {
  const calls: { body: Record<string, unknown> }[] = []
  const fetch = (async (_url: string, init: RequestInit) => {
    calls.push({ body: JSON.parse(String(init.body)) })
    const payload = {
      model: 'vendor/text-model',
      choices: [{ finish_reason: 'stop', message: { content: typeof answer === 'string' ? answer : JSON.stringify(answer) } }],
      usage: { prompt_tokens: 900, completion_tokens: 400, cost: 0.004 },
    }
    return new Response(JSON.stringify(payload), { status: 200, headers: { 'Content-Type': 'application/json' } })
  }) as unknown as typeof globalThis.fetch
  return { calls, fetch }
}

let t: TestStudio

afterEach(async () => {
  await t?.close()
})

async function open(answer: unknown, options: { key?: boolean } = {}) {
  const router = model(answer)
  const bridge = fakeBrowser()
  t = await openTestStudio({
    generation: { apiKey: options.key === false ? undefined : 'test-key', defaultModel: 'vendor/text-model', fetch: router.fetch },
    browser: bridge,
  })
  return { router, bridge }
}

async function catalog(): Promise<Catalog> {
  const { paths, lessons } = await t.workspace.readCatalog()
  const file = JSON.parse(paths.text)
  return { levels: file.levels ?? [], paths: file.paths, lessons: JSON.parse(lessons.text).lessons }
}

const common = ['--title', 'Cottage', '--objective', 'A cottage from a box', '--goal', 'Draw a cottage.', '--source', 'me', '--license', 'CC0']

describe('image to-steps', () => {
  it('generates from a photo and keeps the draft, its photo, its catalog entry and its history', async () => {
    const { router } = await open(JSON.parse(fixture('generation-cottage.json')))
    const photo = path.join(t.root, 'cottage.png')
    await writeFile(photo, PNG)
    const outcome = await t.studio(['image', 'to-steps', photo, '--id', 'cottage', ...common, '--path', 'houses', '--position', '1'])
    expect(outcome.stderr).toBe('')
    expect(outcome.code).toBe(0)
    expect(outcome.stdout).toContain('Generated by vendor/text-model (lesson-v1), $0.0040.')
    expect(outcome.stdout).toContain('Kept as the draft cottage at 1 in "houses", with cottage.png as its reference.')
    expect(router.calls).toHaveLength(1)

    const stored = JSON.parse((await t.workspace.readTutorial('cottage'))!.text) as Tutorial
    expect(stored.id).toBe('cottage')
    expect(stored.title).toBe('Cottage')
    const entry = (await catalog()).lessons.find((l) => l.id === 'cottage')
    expect(entry).toMatchObject({ status: 'draft', objective: 'A cottage from a box', reference: { file: 'cottage.png', source: 'me', license: 'CC0' } })
    expect(entry?.generation).toMatchObject({ model: 'vendor/text-model', promptVersion: 'lesson-v1', goal: 'Draw a cottage.' })
    expect((await catalog()).paths[1].lessonIds).toEqual(['cottage', 'simple-house'])
    const history = await t.workspace.readHistory('cottage')
    expect(history.map((e) => [e.kind, e.kept, e.cost])).toEqual([['generated', true, 0.004]])
    expect((await t.workspace.readReference('cottage.png'))?.bytes.byteLength).toBe(12)
  })

  it('refuses a taken id before asking the model', async () => {
    const { router } = await open({})
    const photo = path.join(t.root, 'p.png')
    await writeFile(photo, PNG)
    const outcome = await t.studio(['image', 'to-steps', photo, '--id', 'simple-house', ...common])
    expect(outcome.code).toBe(1)
    expect(outcome.stderr).toContain('already exists')
    expect(router.calls).toHaveLength(0)
  })

  it('fills a planned lesson, taking its title, objective and place, and dropping its placeholder title', async () => {
    await open(JSON.parse(fixture('generation-cottage.json')))
    const photo = path.join(t.root, 'cottage.png')
    await writeFile(photo, PNG)
    await t.studio(['lessons', 'plan', 'cottage', '--title', 'Cottage', '--objective', 'A cottage from a box', '--path', 'houses', '--position', '1'])

    // Only the photo's provenance and the goal are still needed; the rest comes from the placeholder.
    const outcome = await t.studio(['image', 'to-steps', photo, '--id', 'cottage', '--goal', 'Draw a cottage.', '--source', 'me', '--license', 'CC0'])
    expect(outcome.stderr).toBe('')
    expect(outcome.stdout).toContain('Filled the planned lesson cottage')
    const after = await catalog()
    expect(after.paths.find((p) => p.id === 'houses')?.lessonIds).toEqual(['cottage', 'simple-house'])
    expect(after.lessons.find((l) => l.id === 'cottage')).toMatchObject({
      status: 'draft',
      objective: 'A cottage from a box',
    })
    expect(after.lessons.find((l) => l.id === 'cottage')?.title).toBeUndefined()
    expect((JSON.parse((await t.workspace.readTutorial('cottage'))!.text) as Tutorial).title).toBe('Cottage')
  })

  it('refuses a --path that is not the planned lesson’s own', async () => {
    await open(JSON.parse(fixture('generation-cottage.json')))
    const photo = path.join(t.root, 'cottage.png')
    await writeFile(photo, PNG)
    await t.studio(['lessons', 'plan', 'cottage', '--title', 'Cottage', '--objective', 'A box', '--path', 'houses'])
    const outcome = await t.studio(['image', 'to-steps', photo, '--id', 'cottage', ...common, '--path', 'trees'])
    expect(outcome.code).toBe(2)
    expect(outcome.stderr).toContain('planned in "houses"')
  })

  it('refuses an SVG, and svg to-steps refuses a photo', async () => {
    await open({})
    const svg = path.join(t.root, 'a.svg')
    await writeFile(svg, SVG)
    const photo = path.join(t.root, 'p.png')
    await writeFile(photo, PNG)
    expect((await t.studio(['image', 'to-steps', svg, '--id', 'x', ...common])).stderr).toContain('svg to-steps')
    expect((await t.studio(['svg', 'to-steps', photo, '--id', 'x', ...common])).stderr).toContain('image to-steps')
  })

  it('keeps nothing when the model’s answer is invalid, and can write it out to inspect', async () => {
    const { router } = await open(JSON.parse(fixture('generation-arc.json')))
    const photo = path.join(t.root, 'p.png')
    await writeFile(photo, PNG)
    const out = path.join(t.root, 'bad.json')
    const outcome = await t.studio(['image', 'to-steps', photo, '--id', 'arc', ...common, '--out', out])
    expect(outcome.code).toBe(1)
    expect(outcome.stderr).toContain('not a valid lesson')
    expect(outcome.stderr).toContain('duration')
    expect(router.calls).toHaveLength(1)
    expect(await t.workspace.readTutorial('arc')).toBeNull()
    expect(JSON.parse(await readFile(out, 'utf8'))).toHaveProperty('issues')
  })

  it('says what it would send with --dry-run, and needs a key otherwise', async () => {
    const { router } = await open({}, { key: false })
    const photo = path.join(t.root, 'p.png')
    await writeFile(photo, PNG)
    const dry = await t.studio(['image', 'to-steps', photo, '--id', 'x', ...common, '--dry-run'])
    expect(dry.code).toBe(0)
    expect(dry.stdout).toContain('key missing')
    const real = await t.studio(['image', 'to-steps', photo, '--id', 'x', ...common])
    expect(real.code).toBe(1)
    expect(real.stderr).toContain('OPENROUTER_API_KEY')
    expect(router.calls).toHaveLength(0)
  })
})

describe('svg to-steps', () => {
  const answer = {
    analysis,
    outlineSteps: [{ id: 'top', title: 'The top', instruction: 'Draw the top edge.', strokeIds: ['s1'] }, { id: 'sides', title: 'The sides', instruction: 'Both sides.', strokeIds: ['s2', 's3'] }],
    colourSteps: [{ id: 'paint', title: 'Colour', instruction: 'Colour it.', fillIds: ['f1', 'f2'] }],
  }

  it('traces the file in the browser, sends the trace, and keeps a v2 lesson with the SVG as its reference', async () => {
    const { router, bridge } = await open(answer)
    const svg = path.join(t.root, 'square.svg')
    await writeFile(svg, SVG)
    const outcome = await t.studio(['svg', 'to-steps', svg, '--id', 'square', ...common, '--max-strokes', '32'])
    expect(outcome.stderr).toBe('')
    expect(outcome.code).toBe(0)
    expect(bridge.traced).toBe(1)
    expect(router.calls).toHaveLength(1)
    expect(JSON.stringify(router.calls[0].body)).toContain('s1')

    const stored = JSON.parse((await t.workspace.readTutorial('square'))!.text) as Tutorial
    expect(stored.schemaVersion).toBe(2)
    expect(stored.steps.map((s) => s.id)).toEqual(['top', 'sides', 'paint'])
    expect((await catalog()).lessons.find((l) => l.id === 'square')?.reference?.file).toBe('square.svg')
    expect((await catalog()).lessons.find((l) => l.id === 'square')?.generation?.promptVersion).toBe('svg-lesson-v1')
  })

  it('takes a saved trace instead of tracing again', async () => {
    const { bridge } = await open(answer)
    const svg = path.join(t.root, 'square.svg')
    await writeFile(svg, SVG)
    const saved = path.join(t.root, 'trace.json')
    await writeFile(saved, JSON.stringify(trace()))
    const outcome = await t.studio(['svg', 'to-steps', svg, '--id', 'square', ...common, '--trace', saved])
    expect(outcome.code).toBe(0)
    expect(bridge.traced).toBe(0)
  })

  it('builds a lesson from the trace alone with --no-model, a few lines per step', async () => {
    const { router } = await open(answer)
    const svg = path.join(t.root, 'square.svg')
    await writeFile(svg, SVG)
    const outcome = await t.studio(['svg', 'to-steps', svg, '--id', 'square', '--no-model', '--title', 'Square', '--objective', 'A square', '--source', 'me', '--license', 'CC0'])
    expect(outcome.stderr).toBe('')
    expect(outcome.code).toBe(0)
    expect(outcome.stdout).toContain('without a model')
    expect(router.calls).toHaveLength(0)
    const stored = JSON.parse((await t.workspace.readTutorial('square'))!.text) as Tutorial
    expect(stored.steps.map((s) => [s.id, s.strokes.length, s.fills?.length ?? 0])).toEqual([['lines-1', 3, 0], ['colour', 0, 2]])
    expect((await catalog()).lessons.find((l) => l.id === 'square')?.generation).toBeUndefined()
    expect((await t.workspace.readHistory('square')).map((e) => e.kind)).toEqual(['generated'])
  })

  it('builds the planned steps from the trace and a plan, asking no model, and keeps the draft', async () => {
    const { router, bridge } = await open(answer)
    const svg = path.join(t.root, 'square.svg')
    await writeFile(svg, SVG)
    const plan = path.join(t.root, 'plan.json')
    await writeFile(
      plan,
      JSON.stringify({
        outlineSteps: [
          { id: 'top', title: 'Draw the top', instruction: 'A line across.', strokeIds: ['s1'] },
          { id: 'sides', title: 'Draw the sides', instruction: 'Down from each end.', strokeIds: ['s3', 's2'] },
        ],
        colourSteps: [{ id: 'colour', title: 'Colour it in', instruction: 'Sand, then navy.', fillIds: ['f1', 'f2'] }],
      }),
    )
    const outcome = await t.studio(['svg', 'to-steps', svg, '--id', 'square', '--plan', plan, '--title', 'Square', '--objective', 'A square', '--source', 'me', '--license', 'CC0'])
    expect(outcome.stderr).toBe('')
    expect(outcome.code).toBe(0)
    expect(outcome.stdout).toContain('Built from the trace and your plan.')
    expect(router.calls).toHaveLength(0)
    expect(bridge.traced).toBe(1)
    const stored = JSON.parse((await t.workspace.readTutorial('square'))!.text) as Tutorial
    expect(stored.steps.map((s) => [s.id, s.strokes.map((stroke) => stroke.d), s.fills?.length ?? 0])).toEqual([
      ['top', ['M 100 100 L 300 100'], 0],
      ['sides', ['M 300 100 L 300 300', 'M 100 100 L 100 300'], 0],
      ['colour', [], 2],
    ])
    expect((await catalog()).lessons.find((l) => l.id === 'square')).toMatchObject({ status: 'draft', reference: { file: 'square.svg' } })
    expect((await catalog()).lessons.find((l) => l.id === 'square')?.generation).toBeUndefined()
    expect((await t.workspace.readHistory('square')).map((e) => e.kind)).toEqual(['generated'])
  })

  it('draws the lines a plan lists in reversedStrokeIds from the other end, in the first build', async () => {
    await open(answer)
    const svg = path.join(t.root, 'square.svg')
    await writeFile(svg, SVG)
    const plan = path.join(t.root, 'plan.json')
    await writeFile(
      plan,
      JSON.stringify({
        outlineSteps: [{ id: 'all', title: 'Draw it', instruction: 'All three lines.', strokeIds: ['s1', 's2', 's3'] }],
        colourSteps: [{ id: 'colour', title: 'Colour it in', instruction: 'Both.', fillIds: ['f1', 'f2'] }],
        reversedStrokeIds: ['s2'],
      }),
    )
    const outcome = await t.studio(['svg', 'to-steps', svg, '--id', 'square', '--plan', plan, '--title', 'Square', '--objective', 'A square', '--source', 'me', '--license', 'CC0'])
    expect(outcome.stderr).toBe('')
    expect(outcome.code).toBe(0)
    expect(outcome.stdout).toContain('1 line is drawn from the other end, as the plan asks.')
    const stored = JSON.parse((await t.workspace.readTutorial('square'))!.text) as Tutorial
    expect(stored.steps[0].strokes.map((stroke) => stroke.d)).toEqual(['M 100 100 L 300 100', 'M 100 300 L 100 100', 'M 300 100 L 300 300'])

    await writeFile(plan, JSON.stringify({ outlineSteps: [{ id: 'all', title: 'Draw it', instruction: 'All.', strokeIds: ['s1', 's2', 's3'] }], colourSteps: [], reversedStrokeIds: ['s7'] }))
    const bad = await t.studio(['svg', 'to-steps', svg, '--id', 'square-2', '--plan', plan, '--title', 'Square', '--objective', 'A square', '--source', 'me', '--license', 'CC0'])
    expect(bad.code).toBe(1)
    expect(bad.stderr).toContain('reversedStrokeIds names 1 line id that is not there: s7')
    expect(await t.workspace.readTutorial('square-2')).toBeNull()
  })

  it('refuses a plan naming an id that is not in the trace before anything is written', async () => {
    await open(answer)
    const svg = path.join(t.root, 'square.svg')
    await writeFile(svg, SVG)
    const plan = path.join(t.root, 'plan.json')
    await writeFile(plan, JSON.stringify({ outlineSteps: [{ id: 'all', title: 'All', instruction: 'All of it.', strokeIds: ['s1', 's2', 's9'] }], colourSteps: [] }))
    const outcome = await t.studio(['svg', 'to-steps', svg, '--id', 'square', '--plan', plan, '--title', 'Square', '--objective', 'A square', '--source', 'me', '--license', 'CC0'])
    expect(outcome.code).toBe(1)
    expect(outcome.stderr).toContain('not there: s9')
    expect(await t.workspace.readTutorial('square')).toBeNull()
    expect((await catalog()).lessons.find((l) => l.id === 'square')).toBeUndefined()

    const both = await t.studio(['svg', 'to-steps', svg, '--id', 'square', '--plan', plan, '--no-model', '--title', 'Square', '--objective', 'A square', '--source', 'me', '--license', 'CC0'])
    expect(both.code).toBe(2)
  })

  it('shows and writes the candidate without keeping it, with --no-keep', async () => {
    await open(answer)
    const svg = path.join(t.root, 'square.svg')
    await writeFile(svg, SVG)
    const out = path.join(t.root, 'candidate.json')
    const outcome = await t.studio(['svg', 'to-steps', svg, '--id', 'square', ...common, '--no-keep', '--out', out])
    expect(outcome.code).toBe(0)
    expect(outcome.stdout).toContain('Not kept')
    expect(await t.workspace.readTutorial('square')).toBeNull()
    expect((JSON.parse(await readFile(out, 'utf8')) as { tutorial: Tutorial }).tutorial.id).toBe('square')
  })
})

describe('svg trace --summary', () => {
  it('prints what a model is told about the trace', async () => {
    await open({})
    const svg = path.join(t.root, 'square.svg')
    await writeFile(svg, SVG)
    const summary = await t.json<{ strokes: { id: string; box: number[] }[]; fills: { id: string; color: string }[]; notes: string[]; outlineCoverage: number }>(['svg', 'trace', svg, '--summary'])
    expect(summary.strokes.map((stroke) => stroke.id)).toEqual(['s1', 's2', 's3'])
    expect(summary.strokes[0]).toEqual({ id: 's1', box: [100, 100, 300, 300], length: 200, closed: false, start: [100, 100], end: [300, 100] })
    expect(summary.fills.map((fill) => fill.color)).toEqual(['#E8C872', '#1F3A5F'])
    expect(summary.notes).toEqual(['Traced for the test.'])
    expect(summary.outlineCoverage).toBe(1)
    const outcome = await t.studio(['svg', 'trace', svg, '--summary'])
    expect(outcome.stdout).toContain('3 lines and 2 colours')
    expect(outcome.stdout).toMatch(/s2 {4}100 100 300 300 {2}100,100 → 100,300 {2}200 {5}open/)
    expect(outcome.stdout).toMatch(/f1 {6}#E8C872 {2}40000/)
  })
})

describe('lessons regenerate', () => {
  const answer = {
    rationale: 'Each instruction now says where to start.',
    steps: [
      { id: 'walls', title: 'Walls', instruction: 'Start at the top left.' },
      { id: 'roof', title: 'Roof', instruction: 'Start at the left eave.' },
      { id: 'door', title: 'Door', instruction: 'Centre it.' },
      { id: 'windows', title: 'Windows', instruction: 'Either side.' },
      { id: 'chimney', title: 'Chimney', instruction: 'On the right.' },
    ],
  }

  it('records the regenerated layer in History and leaves the lesson as it was', async () => {
    const { router } = await open(answer)
    const outcome = await t.studio(['lessons', 'regenerate', 'simple-house', '--layer', 'instructions', '--note', 'Say where to start.'])
    expect(outcome.stderr).toBe('')
    expect(outcome.code).toBe(0)
    expect(outcome.stdout).toContain('Rationale: Each instruction now says where to start.')
    expect(router.calls).toHaveLength(1)
    expect(JSON.stringify(router.calls[0].body)).toContain('Say where to start.')
    const history = await t.workspace.readHistory('simple-house')
    expect(history.map((e) => [e.kind, e.layer, e.note])).toEqual([
      ['regenerated', 'instructions', 'Say where to start.'],
      ['saved', undefined, undefined],
    ])
    expect(history[0].tutorial.steps[0].title).toBe('Walls')
    expect((JSON.parse((await t.workspace.readTutorial('simple-house'))!.text) as Tutorial).steps[0].title).toBe('Draw the walls')
  })

  it('makes the regenerated version the lesson with --use', async () => {
    await open(answer)
    const outcome = await t.studio(['lessons', 'regenerate', 'simple-house', '--layer', 'instructions', '--use'])
    expect(outcome.code).toBe(0)
    expect((JSON.parse((await t.workspace.readTutorial('simple-house'))!.text) as Tutorial).steps[0].title).toBe('Walls')
    expect((await t.workspace.readHistory('simple-house')).map((e) => e.kind)).toEqual(['saved', 'regenerated', 'saved'])
  })

  it('needs a reference for a new drawing, and says what it would send with --dry-run', async () => {
    const { router } = await open(answer)
    const missing = await t.studio(['lessons', 'regenerate', 'simple-house', '--layer', 'drawing'])
    expect(missing.code).toBe(1)
    expect(missing.stderr).toContain('has none')
    const dry = await t.studio(['lessons', 'regenerate', 'palm-tree-4', '--layer', 'drawing', '--dry-run'])
    expect(dry.code).toBe(0)
    expect(dry.stdout).toContain('Reference: palm-tree-4.svg (image/svg+xml).')
    expect(router.calls).toHaveLength(0)
  })

  it('regenerates a drawing from an SVG reference through the tracer', async () => {
    const { router, bridge } = await open({
      analysis,
      outlineSteps: [{ id: 'all', title: 'All', instruction: 'All lines.', strokeIds: ['s1', 's2', 's3'] }],
      colourSteps: [{ id: 'paint', title: 'Colour', instruction: 'Colour it.', fillIds: ['f1', 'f2'] }],
    })
    const outcome = await t.studio(['lessons', 'regenerate', 'palm-tree-4', '--layer', 'drawing', '--goal', 'A palm', '--use'])
    expect(outcome.stderr).toBe('')
    expect(outcome.code).toBe(0)
    expect(bridge.traced).toBe(1)
    expect(router.calls).toHaveLength(1)
    const stored = JSON.parse((await t.workspace.readTutorial('palm-tree-4'))!.text) as Tutorial
    expect(stored.steps.map((s) => s.id)).toEqual(['all', 'paint'])
    expect(stored.title).toBe('Palm Tree 4')
  })
})
