// Generated by the Superwall CLI. Commit it; don't edit it, and don't delete it.
// It is what makes `import hero from "./assets/hero.jpg"` typecheck and what
// makes router.push("...") autocomplete and reject typos. `superwall dev`
// rewrites it whenever your app/ directories change.

/// <reference types="superwall/assets" />

declare module "superwall/navigation" {
  interface SuperwallRoutes {
    "index": true;
    "paywall": true;
    "plans": true;
  }
}

export type SuperwallRouteName = keyof import("superwall/navigation").SuperwallRoutes;

declare module "superwall/hooks" {
  interface SuperwallProducts {
    "weekly": true;
    "yearly": true;
  }

  interface SuperwallStripeProducts {
  }
}
